name: Node Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  node-tests:
    if: github.event.pull_request.draft == false
    uses: alleyinteractive/.github/.github/workflows/node-tests.yml@main
    with:
      run-audit: true
      ci: true
      node: 20
